version: "3.8"

services:
  target-server:
    image: nginx:latest
    container_name: target-server
    networks:
      isolated_ddos_net:
        ipv4_address: 192.168.1.10
    ports:
      - "8080:80"
    entrypoint: >
      sh -c "ip route del default &&
             ip route add default via 192.168.1.5 &&
             nginx -g 'daemon off;'"

  attacker1:
    build:
      context: ./attacker
      dockerfile: Dockerfile
    container_name: attacker1
    networks:
      isolated_ddos_net:
        ipv4_address: 192.168.1.20

  attacker2:
    build:
      context: ./attacker
      dockerfile: Dockerfile
    container_name: attacker2
    networks:
      isolated_ddos_net:
        ipv4_address: 192.168.1.21

  attacker3:
    build:
      context: ./attacker
      dockerfile: Dockerfile
    container_name: attacker3
    networks:
      isolated_ddos_net:
        ipv4_address: 192.168.1.22

  monitor:
    build:
      context: ./monitor
      dockerfile: Dockerfile
    container_name: monitor
    networks:
      isolated_ddos_net:
        ipv4_address: 192.168.1.5
    ports:
      - "9000:9000"
    cap_add:
      - NET_ADMIN
    privileged: true
    command: >
      sh -c "iptables -t nat -A PREROUTING -p tcp --dport 80 -j DNAT --to-destination 192.168.1.10 &&
             iptables -t nat -A POSTROUTING -j MASQUERADE &&
             echo 1 > /proc/sys/net/ipv4/ip_forward &&
             sleep infinity"

networks:
  isolated_ddos_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
