# Kali Linux 기반 이미지 사용
FROM kalilinux/kali-rolling

# 패키지 업데이트 및 설치
RUN apt update && \
    apt install -y hping3 && \
    apt install -y iputils-ping && \
    apt install -y snort && \
    apt install -y iptables && \
    apt install -y tshark && \
    apt clean

# 기본 명령을 sleep으로 설정하여 컨테이너 유지
CMD ["sleep", "infinity"]
