version: "3.8"

services:
  target-server:
    build:
      context: ./target-server
      dockerfile: Dockerfile
    container_name: target-server
    networks:
      isolated_ddos_net:
        ipv4_address: 192.168.1.10
    ports:
      - "8080:80"
    cap_add:
      - NET_ADMIN
    privileged: true
    command: >
      sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward &&
             nginx -g 'daemon off;'"

  attacker1:
    build:
      context: ./attacker
      dockerfile: Dockerfile
    container_name: attacker1
    networks:
      isolated_ddos_net:
        ipv4_address: 192.168.1.20

  attacker2:
    build:
      context: ./attacker
      dockerfile: Dockerfile
    container_name: attacker2
    networks:
      isolated_ddos_net:
        ipv4_address: 192.168.1.21

  attacker3:
    build:
      context: ./attacker
      dockerfile: Dockerfile
    container_name: attacker3
    networks:
      isolated_ddos_net:
        ipv4_address: 192.168.1.22

networks:
  isolated_ddos_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
